spring:
  application:
    name: notification
  rabbitmq:
    host: localhost
    port: 5672


server:
  port: 8085

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost
#    prefer-ip-address: true